baseURL       = "https://openmonstervision.github.io/blog/"
title         = "Open Monster Vision"
languageCode  = "en-us"
theme         = "hugo-cards"
contentDir    = "content"
layoutDir     = "layouts"
publishDir    = "docs"
buildDrafts   = false
canonifyURLs  = true
pygmentsuseclasses = true
paginate = 6

[taxonomies]
    category = "categories"
    tag      = "tags"

[params]
    subtitle = "Coding and Stuff"
    author   = "BSDPunk"
    archive  = "archive"
    defaultImage = "gopher.png"
