baseURL = "https://openmonstervision.github.io/blog/"
languageCode = "en-us"
title = "Open Monster Vision"
theme = "hugo-theme-cactus-plus"
contentDir = "content"
layoutDir = "layouts"
publishDir = "docs"
buildDrafts = false
canonifyURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archive"
[params]
  subtitle = "Coding and Stuff"
  author = "BSDPunk and Trozdol"
