baseURL = "public/"
languageCode = "en-us"
title = "Open Monster Vision"
theme = "hugo-theme-cactus-plus"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
canonifyURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  subtitle = "Hugo is Absurdly Fast!"
  author = "John Doe"
